# Generated by Django 5.1.6 on 2025-02-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
