# Generated by Django 5.1.6 on 2025-03-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_discount_tax_item_currency_order_discount_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('rub', 'RUB')], default='usd', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
